language: python

python:
  - "3.6"

cache:
  pip: true

install:
  - pip install codecov
  - pip install pycodestyle

script:
  - coverage run scripts/haddock_param_summary.py test/input/prot-prot-em.json
  - coverage run -a scripts/haddock_param_extract_pdb.py test/input/prot-prot-em.json
  - coverage run -a scripts/haddock_param_replace.py amb_cool2 100 test/input/prot-prot-em.json
  - nosetests --with-coverage
  - pycodestyle --ignore=E402,E501 .

after_success:
  - codecov